// Generated by gencpp from file glass_bridge/glass_serviceRequest.msg
// DO NOT EDIT!


#ifndef GLASS_BRIDGE_MESSAGE_GLASS_SERVICEREQUEST_H
#define GLASS_BRIDGE_MESSAGE_GLASS_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace glass_bridge
{
template <class ContainerAllocator>
struct glass_serviceRequest_
{
  typedef glass_serviceRequest_<ContainerAllocator> Type;

  glass_serviceRequest_()
    : symbol(0)  {
    }
  glass_serviceRequest_(const ContainerAllocator& _alloc)
    : symbol(0)  {
  (void)_alloc;
    }



   typedef uint8_t _symbol_type;
  _symbol_type symbol;





  typedef boost::shared_ptr< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct glass_serviceRequest_

typedef ::glass_bridge::glass_serviceRequest_<std::allocator<void> > glass_serviceRequest;

typedef boost::shared_ptr< ::glass_bridge::glass_serviceRequest > glass_serviceRequestPtr;
typedef boost::shared_ptr< ::glass_bridge::glass_serviceRequest const> glass_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::glass_bridge::glass_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::glass_bridge::glass_serviceRequest_<ContainerAllocator1> & lhs, const ::glass_bridge::glass_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.symbol == rhs.symbol;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::glass_bridge::glass_serviceRequest_<ContainerAllocator1> & lhs, const ::glass_bridge::glass_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace glass_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f8308ac47737d4a6d355ad40cb02765";
  }

  static const char* value(const ::glass_bridge::glass_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f8308ac47737d4aULL;
  static const uint64_t static_value2 = 0x6d355ad40cb02765ULL;
};

template<class ContainerAllocator>
struct DataType< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "glass_bridge/glass_serviceRequest";
  }

  static const char* value(const ::glass_bridge::glass_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char symbol\n"
;
  }

  static const char* value(const ::glass_bridge::glass_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.symbol);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct glass_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::glass_bridge::glass_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::glass_bridge::glass_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "symbol: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.symbol);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLASS_BRIDGE_MESSAGE_GLASS_SERVICEREQUEST_H
