// Generated by gencpp from file glass_bridge/glass_serviceResponse.msg
// DO NOT EDIT!


#ifndef GLASS_BRIDGE_MESSAGE_GLASS_SERVICERESPONSE_H
#define GLASS_BRIDGE_MESSAGE_GLASS_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace glass_bridge
{
template <class ContainerAllocator>
struct glass_serviceResponse_
{
  typedef glass_serviceResponse_<ContainerAllocator> Type;

  glass_serviceResponse_()
    : str()  {
    }
  glass_serviceResponse_(const ContainerAllocator& _alloc)
    : str(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str_type;
  _str_type str;





  typedef boost::shared_ptr< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct glass_serviceResponse_

typedef ::glass_bridge::glass_serviceResponse_<std::allocator<void> > glass_serviceResponse;

typedef boost::shared_ptr< ::glass_bridge::glass_serviceResponse > glass_serviceResponsePtr;
typedef boost::shared_ptr< ::glass_bridge::glass_serviceResponse const> glass_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::glass_bridge::glass_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::glass_bridge::glass_serviceResponse_<ContainerAllocator1> & lhs, const ::glass_bridge::glass_serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.str == rhs.str;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::glass_bridge::glass_serviceResponse_<ContainerAllocator1> & lhs, const ::glass_bridge::glass_serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace glass_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "994972b6e03928b2476860ce6c4c8e17";
  }

  static const char* value(const ::glass_bridge::glass_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x994972b6e03928b2ULL;
  static const uint64_t static_value2 = 0x476860ce6c4c8e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "glass_bridge/glass_serviceResponse";
  }

  static const char* value(const ::glass_bridge::glass_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str\n"
"\n"
;
  }

  static const char* value(const ::glass_bridge::glass_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct glass_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::glass_bridge::glass_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::glass_bridge::glass_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLASS_BRIDGE_MESSAGE_GLASS_SERVICERESPONSE_H
